### ISSUE TITLE
variable

### ISSUE THREAD

**Issue by and09** [afaur/mruby_c_example#1]
Is possible create variable (hook to database)
and get it from C?

or is possible to create object o=Object.new
and modyfy 'o' from C?

**Comment by afaur** [comment]
> Is possible create variable (hook to database) and get it from C?
- Yes this is possible. For instructions on how to accomplish this please take a look at...
  - https://github.com/mruby/mruby/wiki/Building-your-Ruby-environment-and-accessing-it.#access-ruby-from-c
